# Generated by Django 2.1.1 on 2018-09-29 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfoprofile',
            old_name='profile_pic',
            new_name='portfolio_pic',
        ),
    ]
