# Generated by Django 2.1.1 on 2018-09-29 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20180929_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfoprofile',
            old_name='portfolio_pic',
            new_name='profile_pics',
        ),
    ]
